### ISSUE TITLE
生成的clash配置文件有点问题，不是标准的yaml格式的文件

### ISSUE THREAD

**Issue by key1624** [geekdada/surgio#102]
使用的surgio版本 1.24.4
使用的clash.tpl  

```yaml
proxies: {{ getClashNodes(nodeList) | json }}

proxy-groups:
- type: select
  name: 🚀 Proxy
  proxies: {{ getClashNodeNames(nodeList) | json }}
- type: select
  name: 🎬 Netflix
  proxies: {{ getClashNodeNames(nodeList, netflixFilter) | json }}
```

生成的结果

```
proxies: [{"type":"trojan","name":"test","server":"test","port":test,"password":"test","skip-cert-verify":false}]

proxy-groups:
- type: select
  name: 🚀 Proxy
  proxies: ["test"]
```

隐去了一些节点信息，但是应该能看出来生成的节点信息是json而不是按照yaml格式来生成的，希望能帮忙看看，谢谢
