### ISSUE TITLE
[New Features Discussion] Optimize the Clash template file

### ISSUE THREAD

**Issue by nb5p** [geekdada/surgio#48]
将Clash的模板文件写在`surgui.conf.js`不仅有强烈的割裂感，而且不易于管理。对于Clash模板文件的修改方向，我有个不成熟的想法。希望可以在此一起讨论。

```javascript
port: 7890
socks-port: 7891
allow-lan: true

Proxy:
{{ getClashNodes(nodeList) | yamlArrayPatch | indent(1) }}

Proxy Group:
  - { type: 'select', name: '🕹PROXY', proxies: [ '🌏Group1', '🌏Group2', '🌏Group3' ] }
  - { type: 'select', name: '🌏Group1', proxies: {{ getNodeNames(nodeList, customFilters.aFilter) | yamlInlineArrayPatch }} }
  - { type: 'select', name: '🌏Group2', proxies: {{ getNodeNames(nodeList, customFilters.bFilter) | yamlInlineArrayPatch }} }
  - { type: 'select', name: '🌏Group3', proxies: {{ getNodeNames(nodeList, customFilters.cFilter) | yamlInlineArrayPatch }} }

Rule:
- GEOIP,CN,DIRECT
- MATCH,🕹PROXY
```

```yaml
port: 7890
socks-port: 7891
allow-lan: true

Proxy:
  - { type: 'ss', cipher: 'chacha20-ietf', name: 'Node1', password: '000000', port: 1, server: 'example.com', udp: false }
  - { type: 'ss', cipher: 'chacha20-ietf', name: 'Node2', password: '000000', port: 1, server: 'example.com', udp: false }
  - { type: 'ss', cipher: 'chacha20-ietf', name: 'Node3', password: '000000', port: 1, server: 'example.com', udp: false }
  - { type: 'ss', cipher: 'chacha20-ietf', name: 'Node4', password: '000000', port: 1, server: 'example.com', udp: false }
  - { type: 'ss', cipher: 'chacha20-ietf', name: 'Node5', password: '000000', port: 1, server: 'example.com', udp: false }
  - { type: 'ss', cipher: 'chacha20-ietf', name: 'Node6', password: '000000', port: 1, server: 'example.com', udp: false }

Proxy Group:
  - { type: 'select', name: '🕹PROXY', proxies: [ '🌏Group1', '🌏Group2', '🌏Group3' ] }
  - { type: 'select', name: '🌏Group1', proxies: [ 'Node1', 'Node2' ] }
  - { type: 'select', name: '🌏Group2', proxies: [ 'Node3', 'Node4' ] }
  - { type: 'select', name: '🌏Group3', proxies: [ 'Node5', 'Node6' ] }

Rule:
- GEOIP,CN,DIRECT
- MATCH,🕹PROXY
```
